### ISSUE TITLE
need ipa file thank you！

### ISSUE THREAD

**Issue by Index98** [spotlightishere/AvatarStream#1]
Hello Spotlight, I don't have a Mac and can't compile. Can you provide the compiled ipa file? Thank you

**Comment by spotlightishere** [comment]
Hey there - sorry for the long delay! Regretfully, I'm currently not in a position to maintain this repository. I'd recommend possibly asking friends to see if they may be able to compile this repository for you.

Best of luck, and thank you for your interest in this project!
